-- создание таблиц
CREATE TABLE IF NOT EXISTS posts
(
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(256) NOT NULL,
    image   VARCHAR(256) NOT NULL,
    content text         NOT NULL,
    likes   INT
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_id   BIGINT       NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    text      VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS tags
(
    id  BIGINT AUTO_INCREMENT PRIMARY KEY,
    tag VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS post_tags
(
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE
);

